import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar/Navbar";
import { WorkoutProvider } from "../context/WorkoutContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800', '900'], // আপনার যেসব ওয়েট প্রয়োজন
  variable: '--font-montserrat', // কাস্টম CSS ভ্যারিয়েবল (ঐচ্ছিক)
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className={`${montserrat.className} bg-black text-white min-h-screen antialiased`}>
       
        <WorkoutProvider>
         <Navbar/>
          {children}
        </WorkoutProvider>
        
        </body>
    </html>
  );
}
