import { Geist, Geist_Mono, Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar/Navbar";
import { WorkoutProvider } from "../context/WorkoutContext";
import { ToastContainer } from "react-toastify";
import { Toaster } from "react-hot-toast";
import Footer from "../components/footer/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800', '900'], 
  variable: '--font-montserrat', 
  display: 'swap',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body
        className={`${montserrat.className} bg-black text-white min-h-screen antialiased`}
      >
       {/* Toaster Component */}
        <Toaster 
          position="bottom-right" 
          toastOptions={{
            style: {
              background: '#121418',
              color: '#fff',
              border: '1px solid #27272a',
            },
          }}/>

        <WorkoutProvider>
         <Navbar/>
          {children}
          <ToastContainer />
          <Footer/>
        </WorkoutProvider>
        
        </body>
    </html>
  );
}
